[modules_net_cmake.yml] restored build of module.
[.gitlab-ci.yml|bitbucket-pipelines.yml] added testing of net module.

[.gitlab-ci.yml] test core_host_initialize will not run at Debug
configuration for Win32 platform according to the run time error.

[CMakeLists.txt] corrected file names according to expected names from
targets that will use redistributable package. Commented calls of
find_dependency while find Ant4C package.

[bitbucket-pipelines.yml] added build at Alpine Linux.

[gtest.cmake|gtest.cmake] replaced REAL_PATH function with
TO_CMAKE_PATH.

[modules/ant4c.net.framework/CMakeLists.txt] added setting of NETFXSDK
variable.

[modules/net/CMakeLists.txt] restored build of module - project will be
build as independent project.

[modules/net/host_fxr.c] fixed issue at the Win32 platform - missed
calling convertion in definition of get_hostfxr_path_type provoke an
error: Run-Time Check Failure #0 - The value of ESP was not properly
saved across a function call.

[modules/net/net.xml] added support of Win32 environment.

[path.c] replaced functions tmpnam_s and tmpnam with GetTempFileNameW at
the path_get_temp_file_name function.
Added path_get_temp_path_wchar_t function. Changes was made only for
Windows platform.

[tests_base.cmake] added support of CMake version less than 3.13 while
set entry point.

[tests_base.cmake] provided changes that allow to run test of module in
case it was build as independent project.